name: crowdin upload
on:
  push:
    branches: [crowdinUpload2]

jobs:
  CrowdinUpload:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.sha }}
        submodules: 'true'
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11.7
        architecture: x64
    - name: generate pot file
      run: |
        .\miscDeps\tools\xgettext.exe -o "nvda.pot" --package-name "nvda" --package-version "${{ github.sha }}" --foreign-user --add-comments="Translators:" --keyword="pgettext:1c,2" --keyword="npgettext:1c,2,3" --from-code "utf-8" --language="python" source/*.pyw source/**.py
    - name: Upload to Crowdin
      env:
        crowdinProjectID: ${{ secrets.crowdinProjectID }}
        crowdinAuthToken: ${{ secrets.crowdinAuthToken }}
      run: |
        py crowdinSync.py uploadSourceFile 2 nvda.pot nvda.pot
