name: Pre-commit Check

on:
  pull_request:
    types: [ready_for_review]
    branches:
      - master
      - beta
      - rc

jobs:
  pre-commit:
    runs-on: windows-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-precommit')"
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: run pre-commit, fixing issues
        id: pre-commit-fix
        continue-on-error: true
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}

      - name: Commit and push changes from pre-commit
        if: steps.pre-commit-fix.outcome == 'failure'
        run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            # Don't run pre-commit again on the commit
            git commit -m "Apply pre-commit fixes"  --no-verify || echo "No changes to commit"
            git push
